#ask user the books per month from users
books_purchased =float(input("ENTER NUMBER OF BOOKS PURCHASED"))
#EARNING POINTS FROM BOOKS PURCHSED
if books_purchased ==0:
   print("CONGRATULATIONS YOU'VE EARNED;0 POINTS CONTINUE SHOPPING WITH US TO EARN MORE POINTS")
elif books_purchased ==1:
       print("CONGRATULATIONS YOU'VE EARNED;6 POINTS CONTINUE SHOPPING WITH US TO EARN MORE POINTS")
elif books_purchased== 2:
       print("CONGRATULATIONS YOU'VE EARNED;16 POINTS CONTINUE SHOPPING WITH US TO EARN MORE POINTS")
elif books_purchased==3:
       print("CONGRATULATIONS YOU'VE EARNED;32 POINTS CONTINUE SHOPPING WITH US TO EARN MORE POINTS")
elif books_purchased== 4:
       print("CONGRATULATIONS YOU'VE EARNED;60 POINTS CONTINUE SHOPPING WITH US TO EARN MORE POINTS")